title: 안녕하세요!!
email: wndzlf@gmail.com
description: |
baseurl: 'https://wndzlf.github.io'
url: ''
timezone: Asia/Seoul

repository: wndzlf/wndzlf.github.io

permalink: /:year/:month/:day/:title/

excerpt_separator: <!--more-->

markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: '/page/:num/'

collections:
  authors:
    output: true
    permalink: /authors/:path/
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

exclude: [README.md, Gemfile, Gemfile.lock]

keep_files: [assets, files]
github: [metadata]
# iolo's custom
author: wndzlf@gmail.com
image: '/assets/images/sweet-ice-cream-photography-425993.jpg'
asset_url: /assets
#asset_url: //meta-kage.kakaocdn.net/dn/osa/blog/assets
#asset_url: //t1.daumcdn.net/osa/blog/assets
google_analytics:
  ua: 'UA-72007721-1'
facebook:
  app_id: '1204347326263800'
  username: wndzlf
twitter:
  username: wndzlf
google_plus:
  username: wndzlf
github_url:
  username: wndzlf
